# Generated by Django 5.2.8 on 2025-11-29 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Stage', 'Stage'), ('PFE', 'PFE'), ('Premier Emploi', 'Premier Emploi')], max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('is_remote', models.BooleanField(default=False)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField()),
                ('salary_range', models.CharField(blank=True, max_length=100)),
                ('benefits', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
                ('views_count', models.IntegerField(default=0)),
                ('applications_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(limit_choices_to={'role': 'company'}, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
                ('preferred_skills', models.ManyToManyField(blank=True, related_name='preferred_in_offers', to='skills.skill')),
                ('required_skills', models.ManyToManyField(blank=True, related_name='required_in_offers', to='skills.skill')),
                ('targeted_specialties', models.ManyToManyField(blank=True, related_name='offers', to='academic.specialty')),
                ('targeted_universities', models.ManyToManyField(blank=True, related_name='offers', to='academic.university')),
            ],
            options={
                'db_table': 'offers',
                'ordering': ['-created_at'],
            },
        ),
    ]
